version: "3"

volumes:
  vpnsrv_media:

services:
  server:
    build:
      context: .
      dockerfile: deploy/docker/server.Dockerfile
    user: root
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    ports:
      - "${CONTAINER_EXTERNAL_PORT}:${SERVER_LOCAL_PORT}"
    volumes:
      - "${CONTAINER_VOLUME_NAME}:/${CONTAINER_VOLUME_NAME}"
    restart: always
  
  tgbot:
    environment:
      - TGBOT_TOKEN=${TGBOT_TOKEN}
      - TGBOT_ADMIN_USERNAME=${TGBOT_ADMIN_USERNAME}
    build:
      context: .
      dockerfile: deploy/docker/tgbot.Dockerfile
    user: root
    volumes:
      - "${CONTAINER_VOLUME_NAME}:/${CONTAINER_VOLUME_NAME}"
    restart: always

