#!/bin/bash

mkdir -p $SERVER_PKI_DIR
mkdir -p $SERVER_PKI_CERTS_DIR
mkdir -p $SERVER_PKI_INDEX_DIR
mkdir -p $SERVER_PKI_PRIVATE_DIR
touch $SERVER_PKI_INDEX

cat "openssl.conf" | envsubst > $SERVER_PKI_CONF

openssl dhparam -out $PKI_SERVER_DH_CERT 2048

openssl req -config $SERVER_PKI_CONF \
  -newkey rsa:2048 -nodes -keyout $PKI_CA_KEY \
  -x509 -days 3000 -extensions root_ca -out $PKI_CA_CERT \
  -subj "/CN=${PKI_CA_CN}"

echo  00 > $SERVER_PKI_CRLNUM
openssl ca -config $SERVER_PKI_CONF -gencrl -out $SERVER_PKI_CRL

openssl req -config $SERVER_PKI_CONF \
  -newkey rsa:2048 -nodes -keyout $PKI_SERVER_KEY \
  -out $PKI_SERVER_CSR \
  -subj "/CN=${PKI_SERVER_CN}"

openssl ca -config $SERVER_PKI_CONF -batch -create_serial \
  -extensions server_cert -days 3000 -notext \
	-in $PKI_SERVER_CSR \
	-out $PKI_SERVER_CERT

rm -f $PKI_SERVER_CSR

openvpn --genkey --secret $PKI_SERVER_TA_KEY
