#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <config>"
  exit 1
fi

CONFIG_DIR=$1
. $CONFIG_DIR/config

mkdir -p $PKI_DIR
pushd $PKI_DIR
  openssl req -newkey rsa:2048 -nodes -keyout $PKI_CA_KEY -x509 -days 3654 -out $PKI_CA_CERT -subj "/CN=${PKI_CA_CN}"
  openssl dhparam -out $PKI_DH_CERT 2048

  openssl req -newkey rsa:2048 -nodes -keyout $PKI_SERVER_KEY -out $PKI_SERVER_CSR -subj "/CN=${PKI_SERVER_CN}"
  openssl x509 -req -in $PKI_SERVER_CSR -CA $PKI_CA_CERT -CAkey $PKI_CA_KEY -out $PKI_SERVER_CERT -days 3654

  openvpn --genkey --secret $PKI_TA_KEY
popd
