#!/bin/bash

mkdir -p /var/log/openvpn
touch /var/log/openvpn/status.log

mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

pushd $SERVER_DIR
  openvpn \
    --status /var/log/openvpn/status.log \
    --status-version 2 \
    --suppress-timestamps \
    --config $SERVER_CONF
popd