---
- hosts: servers
  become: true
  #roles:
  #  - docker
  tasks:
    - name: Ensure /root/deploy/vpn directory exists.
      file:
        path: /root/deploy/vpn
        state: directory
        mode: 0755
        
    - name: Copy deployment files to the host
      copy:
        src: ../../{{ item.src }}
        dest: /root/deploy/vpn/{{ item.dest }}
        owner: root
        group: root
        mode: 0644
      loop:
        - src: deploy/docker-compose.yml
          dest: docker-compose.yml
        - src: config
          dest: config
    
    - name: Pull containers from Docker Hub
      shell: |
        . ./config
        docker compose pull
      args:
        chdir: /root/deploy/vpn
    
    - name: Run Docker Compose standalone configuration
      shell: |
        . ./config
        docker compose stop
        TGBOT_TOKEN="{{ lookup('env', 'TGBOT_TOKEN') }}" \
        TGBOT_ADMIN_USERNAME="{{ lookup('env', 'TGBOT_ADMIN_USERNAME') }}" \ 
          docker compose up -d
      args:
        chdir: /root/deploy/vpn